[whisper]
model = "large-v2"
device = "cpu"
thread_count = 5  # 5 is default
batch_size = 28
beam_size = 5  # 5 is default
compute_type = "float32"
language = "de"  # Set to None for automatic language detection.

[email]
smtp_server = "mail.example.com"
smtp_port = 25
from = "notifications@example.com"
to = ["alice@example.com", "bob@example.com"]
