[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "transcribe"
license = {file = "LICENSE"}
authors = [
    {name = "Marc Altmann", email = "marc.altmann@cedis.fu-berlin.de"},
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
requires-python=">=3.10"
dynamic = ["version", "description"]
dependencies = [
    "click==8.1.7",
]

[project.optional-dependencies]
test = [
    "pytest",
    "faker",
    "tox",
    "coverage",
    "pytest-cov",
]

[project.urls]
Home = "https://github.com/asr4memory/asr-transcribe"

[project.scripts]
transcribe = "transcribe:transcribe_cli"
