[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "transcribe"
license = {file = "LICENSE"}
authors = [
    {name = "Marc Altmann", email = "m.altmann@fu-berlin.de"},
    {name = "Tobias Kilgus", email = "tobias.kilgus@fu-berlin.de"},
    {name = "Peter Kompiel", email = "peter.kompiel@fu-berlin.de"},
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
requires-python=">=3.10"
dynamic = ["version", "description"]
dependencies = [
    "click==8.1.7",
    "colorlog==6.8.2",
    "Mako==1.3.5",
    "toml==0.10.2",
    "xhtml2pdf==0.2.15",
]

[project.optional-dependencies]
test = [
    "coverage",
    "pylint==3.2.0",
    "pytest-cov",
    "pytest==8.2.0",
    "tox",
]

[project.urls]
Home = "https://github.com/asr4memory/asr-transcribe"

[project.scripts]
transcribe = "transcribe:transcribe_cli"
